### ISSUE TITLE
adapt modules for snakemake 8

### ISSUE THREAD

**Issue by burtonjake** [epigen/mr.pareto#13]
To bump all modules to snakemake 8 (#12) we primarily need to document the libraries required to process the initial Snakemake file. These should be added to `envs/global.yaml` and cross-linked into the Snakemake file with a `conda` directive. See ['global workflow dependencies'](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#global-workflow-dependencies) in the snakemake docs. We also need to check the documentation for each module such that it makes sense for Snakemake8.

one-off (first in unsupervised_analysis)
- [x] create `envs/global.yaml`  specifying required software for Snakefile execution
- [x] create workflow-profile `config.yaml`

for each module

- [x] remove `partition` parameter from `params`
  - Snakefile
  - all rule files
  - config
- [x] add workflow-profile with partition info (cemm's slurm specific) `workflow/profiles/default/config.yaml`
  ```
  cp -R ../unsupervised_analysis/workflow/profiles ./workflow/
  ```
- [x] add `config/README.md`
  ```
  Set workflow-specific `resources` or command line arguments (CLI) in the workflow profile `workflow/profiles/default.config.yaml`, which supersedes global Snakemake profiles.
  ```
- [x] add `envs/global.yaml` to workflow
  ```
  cp ../unsupervised_analysis/workflow/envs/global.yaml ./workflow/envs/
  ```
- [x] use `conda` directive in `Snakefile` for global specifications at the beginning of your workflow, before you import or use any of those additional packages
  ```yaml
  ##### global workflow dependencies #####
  conda: "envs/global.yaml"
  ```
- [x] use min version directive in Snakefile `8.20.1`
  ```python
  ##### set minimum snakemake version #####
  min_version("8.20.1")
  ```
- [x] Document in every module's README the Snakemake version it was tested in.

### Modules
- [x] [Unsupervised Analysis](https://github.com/epigen/unsupervised_analysis)
- [x] [Split, Filter, Normalize and Integrate Sequencing Data](https://github.com/epigen/spilterlize_integrate)
- [x] [Differential Analysis Using limma](https://github.com/epigen/dea_limma)
- [x] [Enrichment Analysis](https://github.com/epigen/enrichment_analysis)
- [x] [Genome Track Visualization](https://github.com/epigen/genome_tracks)
- [x] [scRNA-seq Processing using Seurat](https://github.com/epigen/scrnaseq_processing_seurat)
- [x] [Differential Analysis using Seurat](https://github.com/epigen/dea_seurat)
- [x] [Perturbation Analysis using Mixscape from Seurat](https://github.com/epigen/mixscape_seurat)
- [x] [ATAC-seq Processing](https://github.com/epigen/atacseq_pipeline)

**Comment by sreichl** [comment]
Let's find out which packages actually come with the minimal snakemake installation (the one that would create a problem because of missing packages). e.g., is yaml/pyaml for sure in there? then we could make one `global.yaml` and just copy paste it into every module.

**Comment by sreichl** [comment]
I checked the RNA pipeline again and interestingly they only use the `resource` key once here: https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/993dcfcf3c1210f75f6bfb0ef765a4ddb77cadf7/workflow/rules/ref.smk#L51

in all other rules they only use the `threads` key.

Unsure what to do ie how to decouple resource specifications form workflow configuration meaningfully without adding complexity dor the enduser.
